name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install frontend dependencies
        working-directory: ./frontend  # Change to your frontend directory
        run: |
          npm install
          npm run build --no-lint

      - name: Install backend dependencies
        working-directory: ./backend  # Change to your backend directory
        run: |
          npm install

      - name: Deploy frontend to Firebase
        working-directory: ./frontend  # Change to your frontend directory
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_FRONTEND_TOKEN }}

      - name: Deploy backend to Firebase
        working-directory: ./backend  # Change to your backend directory
        run: |
          firebase deploy --only hosting, functions --token ${{ secrets.FIREBASE_BACKEND_TOKEN }}
