name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run build --no-lint

      - name: Install backend dependencies
        working-directory: ./backend/functions
        run: |
          npm install

      - name: Deploy frontend to Firebase
        working-directory: ./frontend
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_FRONTEND_TOKEN }}

      - name: Deploy backend to Firebase
        working-directory: ./backend
        run: |
          firebase deploy --only functions,hosting --token ${{ secrets.FIREBASE_BACKEND_TOKEN }}

      - name: Start Docker containers
        run: |
          docker-compose up -d # This assumes a docker-compose.yml file exists

      - name: Wait for Prometheus and Grafana to be ready
        run: |
          echo "Waiting for Prometheus and Grafana to start..."
          sleep 30 # Adjust sleep time as needed

      - name: Verify Prometheus and Grafana are running
        run: |
          curl -f http://localhost:9090/api/v1/targets || exit 1 # Check Prometheus
          curl -f http://localhost:3000/api/search || exit 1 # Check Grafana

      - name: Stop Docker containers
        run: |
          docker-compose down
