name: Build and Deploy to Docker (Staging)

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run build --no-lint

      - name: Install backend dependencies
        working-directory: ./backend/functions
        run: |
          npm install

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for frontend
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:staging .

      - name: Build Docker image for backend
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:staging .

      - name: Push frontend image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:staging

      - name: Push backend image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:staging
