name: Lint and Test
on:
  push:
    branches:
      - 'testing'  # or the specific branch you want this to run on
  pull_request:
    branches:
      - 'testing'  # or the specific branch you want this to run on
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          if [ -f package.json ] && grep -q '"test"' package.json; then
            npm test || true # Prevent failing if no tests exist
          fi
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run frontend tests
        run: |
          cd frontend
          if [ -f package.json ] && grep -q '"test"' package.json; then
            npm test || true # Prevent failing if no tests exist
          fi
